name: gitops

on:
  push:
    branches:
      - dev
      - stg
      - main

jobs:
  build-and-update-manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        id: docker
        run: |
          IMAGE_NAME=arunvel1988/backstage-demo
          BRANCH_NAME=${GITHUB_REF##*/}
          TAG=${BRANCH_NAME}-${GITHUB_SHA::7}
          FULL_IMAGE="$IMAGE_NAME:$TAG"

          echo "Building image: $FULL_IMAGE"
          docker build -t $FULL_IMAGE .
          docker push $FULL_IMAGE

          # Set output for later steps
          echo "::set-output name=image::$FULL_IMAGE"

      - name: Checkout manifests repo
        uses: actions/checkout@v3
        with:
          repository: arunvel1988/backstage-flask-catalog-demo-manifests
          path: manifests
          token: ${{ secrets.GITHUB }}

      - name: Update deployment.yaml image
        run: |
          IMAGE=${{ steps.docker.outputs.image }}
          echo "Updating deployment.yaml to use image: $IMAGE"
          sed -i "s|^\(\s*image:\s*\).*|\1$IMAGE|" manifests/manifests/deployment.yaml
          cat manifests/manifests/deployment.yaml

      - name: Commit & Push updated manifests
        run: |
          cd manifests/manifests
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to $IMAGE" || echo "No changes to commit"
          git push
